# Brewfile

# Terminal
cask "ghostty"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# CLI Tools
brew "zoxide"
brew "fd"
brew "fzf"
brew "ripgrep"
brew "bat"
brew "eza"

# Music Player
brew "cmus"

# Nvim
brew "nvim"
brew "tree-sitter-cli"

# MacOS essentials
cask "bettertouchtool"
# cask "contexts"
cask "bleunlock"
cask "rectangle-pro"
cask "karabiner-elements"

