# Brewfile

# Terminal
cask "ghostty"

# CLI Tools
brew "zoxide"
brew "fd"
brew "fzf"
brew "ripgrep"
brew "bat"

# Nvim
brew "nvim"


# MacOS essentials
cask "bettertouchtool"
cask "contexts"
cask "bleunlock"
cask "rectangle-pro"
cask "karabiner-elements"

