require("mini.icons").setup()
require("mini.files").setup()
require("mini.pick").setup()
require("mini.extra").setup()
require("mini.statusline").setup()
require("mini.git").setup()
require("mini.diff").setup()
