format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$character"""

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = false

[git_branch]
style = "bold purple"

[git_status]
style = "bold red"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
