alias v='nvim'
alias vim='nvim'
alias vi='nvim'
alias ls='eza --color=always --icons=always'
alias ll='eza -l --long --git --color=always --no-permissions --icons=always --no-user --no-time'
alias la='eza -la --long --git --color=always --no-permissions --icons=always --no-user --no-time'
alias tree='eza --tree'
alias cpdir='cp -R'
alias cat='bat'
#alias cd='z'
